// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Reto_09_tareas.Models;

public partial class RetoTareasDBContext : DbContext
{
    public RetoTareasDBContext()
    {
    }

    public RetoTareasDBContext(DbContextOptions<RetoTareasDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Tareas> Tareas { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    //#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=WIN-BNES3C0B631;Initial Catalog=RetoTareasDB;Persist Security Info=True;TrustServerCertificate=True;Encrypt=True;MultipleActiveResultSets=true;User ID=UTSC_USER;Password=S1stem@5.UTSC2025");
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Tareas>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Tareas__3214EC073944318C");

            entity.Property(e => e.Titulo)
                .IsRequired()
                .HasMaxLength(100);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}