// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Reto_09_tareas.Models;

public partial class Tareas
{
    public int Id { get; set; }

    public string Titulo { get; set; }

    public bool Completada { get; set; }
}